# iljin
server.port=8041

# iljin
server.servlet.session.cookie.name=iljin_jsessionid

# iljin
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.jdbc-url=${ILJIN_DB_URL}


spring.datasource.hikari.username=${ILJIN_DB_USERNAME}
spring.datasource.hikari.password=${ILJIN_DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maxLifetime = 1800000
spring.datasource.hikari.idle-timeout = 600000
spring.datasource.hikari.leak-detection-threshold=60000

